# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Growinggreen-admin"
license = "MIT"
licenselink = "https://github.com/presence-web-services/growinggreen-admin-site/themes/growinggreen/LICENSE"
description = "Theme for Growing Green Tree Care & Landscaping admin website"
homepage = "http://admin.growinggreentrees.net/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
